### ISSUE TITLE
求助安装后PHP错误

### ISSUE THREAD

**Issue by Qiaofanxing** [donwa/oneindex#367]
报错
Fatal error: Uncaught Error: Call to a member function exists() on boolean in /www/wwwroot/drive_nymphh_com/lib/RedisDrive.php:65 Stack trace: #0 /www/wwwroot/drive_nymphh_com/init.php(83): RedisDrive->exists() #1 /www/wwwroot/drive_nymphh_com/controller/IndexController.php(164): cache('dir_/') #2 /www/wwwroot/drive_nymphh_com/controller/IndexController.php(18): IndexController->items('/') #3 /www/wwwroot/drive_nymphh_com/lib/route.php(33): IndexController->__construct() #4 /www/wwwroot/drive_nymphh_com/index.php(63): route::__callstatic('ANY', Array) #5 {main} thrown in /www/wwwroot/drive_nymphh_com/lib/RedisDrive.php on line 6

**Comment by Qiaofanxing** [comment]
弄错了（捂脸）
